"""add model_reward_posteriors table

Revision ID: e274a67cfc61
Revises: d4c76780952d
Create Date: 2026-10-08 10:41:00.132122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e274a67cfc61'
down_revision: Union[str, Sequence[str], None] = 'd4c76780952d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_reward_posteriors',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('beta_param', sa.Float(), nullable=True),
    sa.Column('total_samples', sa.Integer(), nullable=True),
    sa.Column('positive_feedback', sa.Integer(), nullable=True),
    sa.Column('negative_feedback', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_reward_posteriors_model_id'), 'model_reward_posteriors', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_reward_posteriors_task_type'), 'model_reward_posteriors', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_reward_posteriors_task_type'), table_name='model_reward_posteriors')
    op.drop_index(op.f('ix_model_reward_posteriors_model_id'), table_name='model_reward_posteriors')
    op.drop_table('model_reward_posteriors')
    # ### end Alembic commands ###
